#!/usr/bin/perl
use strict;
use warnings;
my $base = "/data/chris/tyto/20240518";
my $tbl = "m64_all_tab_map_MoFa_reclassify.txt";
local *IN;
my %P;
open IN, $tbl or die "Can't open $tbl : $!";
while ( <IN> ) {
  my @F = split /\t/;
  $P{$F[1]} = $F[7];
}
close IN;
mkdir "${base}Fa";
mkdir "${base}Mo";
for my $kind ("other", "musat", "centromers", "kinetochores", "telomers") {
  local *OF;
  local *OM;
  local *OO;
  open OF, "| gzip --fast >${base}Fa/$kind.fq.gz" or die "Can't create ${base}Fa/$kind.fq.gz : $!";
  open OM, "| gzip --fast >${base}Mo/$kind.fq.gz" or die "Can't create ${base}Mo/$kind.fq.gz : $!";
  open OO, "| gzip --fast >${base}Fa/Unslct.$kind.fq.gz" or die "Can't create ${base}Fa/Unslct.$kind.fq.gz : $!";
  open IN, "gzip -dc $kind.fq.gz |" or die "Can't read $kind.fq.gz : $!";
  while ( <IN> ) {
    my $h = substr $_, 1;
    $h =~ s/\s.*$//s;
    my $s = <IN>;
    my $p = <IN>;
    my $q = <IN>;
    die "grmp $h" unless defined $P{$h};
    if ($P{$h} eq "Father") {
      print OF $_, $s, $p, $q;
    } elsif ($P{$h} eq "Mother") {
      print OM $_, $s, $p, $q;
    } else {
      print OO $_, $s, $p, $q;
    }
  }
  close IN;
  close OO;
  close OM;
  close OF;
}
exit 0;
__END__
==> m64_all_tab_map_MoFa_reclassify.txt <==
id	fqid	kind	len	rounds	qual	parent	reclassify	Faqstart	Faqend	Fastrand	Fatctg	...
00000000	m64046_200313_184523/12/ccs	other	11123	10	0.999566	Unknown	Mother	0	11123	+	Fa_000164l	...
00000001	m64046_200313_184523/14/ccs	other	13496	14	0.999817	Mother	Mother	9	13495	-	Fa_000028l	...
00000002	m64046_200313_184523/44/ccs	other	16108	14	0.999542	Mother	Mother	13	16104	-	Fa_000013l	...

==> other.fq.gz /dev/fd/63 <==
@m64046_200313_184523/12/ccs
CGAGTTGTGGGAGCTGCATGGTGACAGGGCCCACAAGGGGACTTGTGTGGCTGAGACCTTACCCGTTCAGCTCACAATTCTGGCCACTCTCAATCAAAGC...
+
~u~r~~o~f~~~~~~~~~~s~~b~~~k~~Z~~~~~~L~~~~~~~~~~~s~|~~~N~x~Y~~X~~~i~~~~~~~~~~~x~~~i~~~~~~~~v~~~~y~~~~...
@m64046_200313_184523/8325444/ccs
TTGATGGCACATGGGCAGCCTGGCTGGAGTGCAGTGTGACTTCTCGGTACCTTTCCTTCTTCACTGGGGCATGTTTGAAACCTACTGCAACGAATAACTG...
+
~~~~~~~~~~~~N~~~~~~~~\~~~~~~~~~~~~x~~~~~~~~~~~~~~~~v~~~~~~~~~~~~~G~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...

==> musat.fq.gz /dev/fd/62 <==
@m64046_200313_184523/153422550/ccs
GATGCCCAGACGGTGCTAGCAAAAGCGATGAGCAGGAGAAAGGCTCTTCGGGACAATGTTTTCCTTGGCTAACAAGGAAGGGATGGATGTCCTTGAGTGT...
+
~ddiK~~n<YbLtaVWE,DbBxxsehge\hrRgpQ~rLEuTV~drK^~hL~~]UZwZ_>tUTUzYj,UKe]~g`w:~Q[+eVdS7\XeguB~G~drfraW...
@m64046_200313_184523/170919396/ccs
CATAGAATGCCACATGGAAAGGCCAGAGGTCTTCAAGAGCAGGCTAGACAAACTCCTGCCAGGATGGGCACAGACACCTCTGCTCCAGCCTTGGGGCAGG...
+
~~~~~~~~rz~~~~~y~v~~t~\~~~~u~~}~~~r~t~t~~q~~~~~~~b~~~~h~~~s~~r~~~E~~~~~~r~l~k~~}~~~~e~~{t~~~-~~~~~x~...
