#!/bin/bash
base=/data/chris/tyto/20240518
for f in m64*.fa.gz; do
  n=`basename $f .hifi_reads.fa.gz`
  if [[ -s ${base}Fa/$n.paf ]]; then
    echo "Sample $n already mapped - skipping"
  else
    echo "Processing sample $n"
    minimap2 -t 40 -x map-hifi ${base}Fa/asm.p_ctg.fa $f >${base}Fa/$n.paf
    minimap2 -t 40 -x map-hifi ${base}Mo/asm.p_ctg.fa $f >${base}Mo/$n.paf
  fi
done
exit 0

m64046_200313_184523.hifi_reads.fa.gz
m64046_200512_231235.hifi_reads.fa.gz
m64156_220708_235329.hifi_reads.fa.gz
m64156_220712_124431.hifi_reads.fa.gz
m64156_230805_122943.hifi_reads.fa.gz
